# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - papermark

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    env:
      WEBSITE_ENABLE_LOGGING: true
      WEBSITES_ENABLE_APP_SERVICE_STORAGE: true

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_120981CCFEA044749073A8EFC66635F1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_16813D759948431ABAF7D41D4742D2EC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FDF13084E37D41D4ADB13CFC06877FCB }}

      - name: Stop Azure Web App before deployment
        run: |
          az webapp stop --name papermark --resource-group David_rebricole
          echo "⏳ Attente que l'application soit complètement arrêtée..."
          for i in {1..30}; do
            STATUS=$(az webapp show --name papermark --resource-group David_rebricole --query "state" -o tsv)
            echo "État actuel : $STATUS"
            if [ "$STATUS" = "Stopped" ]; then
              echo "✅ Application stoppée."
              break
            fi
            echo "⏳ Encore active, nouvelle vérification dans 5 secondes..."
            sleep 5
          done
          FINAL_STATUS=$(az webapp show --name papermark --resource-group David_rebricole --query "state" -o tsv)
          if [ "$FINAL_STATUS" != "Stopped" ]; then
            echo "❌ L'application n'a pas pu être stoppée. Abandon du déploiement."
            exit 1
          fi

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'papermark'
          slot-name: 'Production'
          package: .

      - name: Start Azure Web App after deployment
        run: az webapp start --name papermark --resource-group David_rebricole

      - name: Voir les logs récents de démarrage
        run: |
          echo "📦 Affichage des 20 dernières secondes de logs..."
          timeout 20s az webapp log tail --name papermark --resource-group David_rebricole || echo "✅ Fin des logs (timeout attendu)"
